/** @jsxImportSource @emotion/react */
import { css, jsx } from "@emotion/react";
import Head from "next/head";
import { Image, Scroll, useScroll } from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";
import { ScrollControls } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { useRef } from "react";

function Images() {
  const { width, height } = useThree((state) => state.viewport);
  const group = useRef();
  const data = useScroll();
  useFrame(() => {
    group.current.children[0].material.zoom = 1 + data.range(0, 1 / 3) / 2;
    group.current.children[1].material.zoom = 1 + data.range(0, 1 / 3) / 2;
    group.current.children[2].material.zoom = 1 + data.range(1 / 3, 2 / 3);
    group.current.children[3].material.zoom = 1 + data.range(1 / 3, 2 / 3);
  });

  return (
    <group ref={group}>
      <Image url="/img/img1.jpg" scale={[4, 5, 1]} position={[-1, 0, 1]} />
      <Image url="/img/img2.jpg" scale={3} position={[2, 0, 1]} />
      <Image
        url="/img/img3.jpg"
        scale={[1, 3.5, 1]}
        position={[2.3, -height, 2]}
      />
      <Image
        url="/img/img4.jpg"
        scale={[1.4, 2, 1]}
        position={[-1.3, -height - 0.3, 3.2]}
      />
    </group>
  );
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={canvasStyle}>
        <Canvas>
          <ScrollControls pages={3} damping={3}>
            <Scroll>
              <Images />
            </Scroll>
            <Scroll html>
              <h1
                style={{ position: "absolute", top: "60vh", left: "1.5em" }}
                css={h1Style}
              >
                Be
              </h1>
              <h1
                style={{ position: "absolute", top: "140vh", left: "40vw" }}
                css={h1Style}
              >
                Creative
              </h1>
            </Scroll>
          </ScrollControls>
        </Canvas>
      </div>
    </div>
  );
}

const canvasStyle = css({
  height: "100vh",
  width: "100%",
  margin: "0",
  padding: "0",
  background: "#efefef",
});

const h1Style = css({
  fontSize: "12em",
  fontWeight: "400",
  letterSpacing: "-0.05em",
  lineHeight: "0.7em",
  margin: "0",
  padding: "0",
  color: "white",
  textShadow: "1px 0px 35px #383838",
});
